#!/bin/bash

echo
echo "sript pour tester Mcat."
echo
echo "cas 1 : Mcat simple (ctrl+D pour sortir)"
./Mhead
echo "cas 2 : ls | Mcat"
ls | ./Mhead
echo "cas 3 : redirection dans un fichier"
./Mhead > MonFichierHead
echo "cas 4 : ls | Mcat >> fichier"
ls | ./Mhead >> MonFichierHead2
echo "cas 5 : Mcat < file"
./Mhead < MonFichierHead
echo "Fin des tests"