#!/bin/bash

#codes couleur
C='\033[44m'
E='\033[32m\033[1m'
N='\033[0m'

echo "Commande echo écrite en c : Mecho"
echo "---------------------------------"
echo -e "Éxecution de ${E}echo coucou${N} :"
echo coucou
echo -e "Éxecution de ${E}./Mecho coucou${N} :"
./Mecho coucou
echo -e "${C}             --> Enter pour continuer${N}"
read
echo -e "Éxecution de ${E}echo un deux trois${N} :"
echo un deux trois
echo -e "Éxecution de ${E}./Mecho un deux trois${N} :"
./Mecho un deux trois
echo -e "${C}             --> Enter pour continuer${N}"
read
echo -e "Execution de ${E}echo une phrase complete > fichier${N} :"
echo une phrase complète > fichier
echo -e "Execution de ${E}./Mecho une phrase complete > fichier${N} :"
./Mecho une phrase complète > fichier
echo -e "${C}             --> Entrer pour continuer${N} :"
read
echo -e "Execution de ${E}echo coucou >> fichier${N} :"
echo coucou >> fichier
echo -e "Execution de ${E}./Mecho coucou >> fichier${N} :"
./Mecho coucou >> fichier
echo -e "${C}             --> Entrer pour continuer${N} :"
read
echo -e "Execution de ${E}echo coucou | wc -c${N} :"
echo coucou | wc -c
echo -e "execution de ${E}./Mecho coucou | wc -c${N} :"
./Mecho coucou | wc -c
echo -e "${C}             --> Entrer pour continuer${N} :"
read
echo -e "Execution de ${E}echo *${N} :"
echo *
echo -e "execution de ${E}./Mecho *${N} :"
./Mecho *
echo -e "${C}             --> Entrer pour continuer${N} :"
read
